FROM node:12.18.4

WORKDIR /app

RUN npm install -g @vue/cli

CMD ["/bin/sh"]

# COPY ./vue-project/package*.json /app/
# RUN npm install
# RUN npm install --save axios
# RUN npm install --save vuex-persistedstate
